// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// edt_cpp
NumericMatrix edt_cpp(LogicalMatrix mask);
RcppExport SEXP _MycoHalo_edt_cpp(SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(edt_cpp(mask));
    return rcpp_result_gen;
END_RCPP
}
// label_cpp
IntegerMatrix label_cpp(LogicalMatrix mask, int connectivity);
RcppExport SEXP _MycoHalo_label_cpp(SEXP maskSEXP, SEXP connectivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type connectivity(connectivitySEXP);
    rcpp_result_gen = Rcpp::wrap(label_cpp(mask, connectivity));
    return rcpp_result_gen;
END_RCPP
}
// box_sum_cpp
NumericMatrix box_sum_cpp(NumericMatrix x, int r);
RcppExport SEXP _MycoHalo_box_sum_cpp(SEXP xSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(box_sum_cpp(x, r));
    return rcpp_result_gen;
END_RCPP
}
// watershed_cpp
IntegerMatrix watershed_cpp(NumericMatrix cost, IntegerMatrix markers, LogicalMatrix mask);
RcppExport SEXP _MycoHalo_watershed_cpp(SEXP costSEXP, SEXP markersSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type markers(markersSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(watershed_cpp(cost, markers, mask));
    return rcpp_result_gen;
END_RCPP
}
// box_blur_cpp
NumericMatrix box_blur_cpp(NumericMatrix x, int r, int passes);
RcppExport SEXP _MycoHalo_box_blur_cpp(SEXP xSEXP, SEXP rSEXP, SEXP passesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type passes(passesSEXP);
    rcpp_result_gen = Rcpp::wrap(box_blur_cpp(x, r, passes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MycoHalo_edt_cpp", (DL_FUNC) &_MycoHalo_edt_cpp, 1},
    {"_MycoHalo_label_cpp", (DL_FUNC) &_MycoHalo_label_cpp, 2},
    {"_MycoHalo_box_sum_cpp", (DL_FUNC) &_MycoHalo_box_sum_cpp, 2},
    {"_MycoHalo_watershed_cpp", (DL_FUNC) &_MycoHalo_watershed_cpp, 3},
    {"_MycoHalo_box_blur_cpp", (DL_FUNC) &_MycoHalo_box_blur_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MycoHalo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
