# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Exact Euclidean distance transform (internal)
#'
#' @param mask Logical matrix. For every TRUE pixel the Euclidean distance
#'   (in pixels) to the nearest FALSE pixel is returned; FALSE pixels get 0.
#' @return Numeric matrix of distances. If the mask contains no FALSE pixel,
#'   all values are Inf.
#' @keywords internal
#' @noRd
edt_cpp <- function(mask) {
    .Call(`_MycoHalo_edt_cpp`, mask)
}

#' Connected-component labelling (internal)
#'
#' @param mask Logical matrix.
#' @param connectivity 4 or 8.
#' @return Integer matrix; 0 = background, 1..n = components numbered in
#'   raster (column-major) order of first appearance.
#' @keywords internal
#' @noRd
label_cpp <- function(mask, connectivity = 8L) {
    .Call(`_MycoHalo_label_cpp`, mask, connectivity)
}

#' Moving-window sum over a (2r+1) x (2r+1) square (internal)
#'
#' Windows are clipped at the image border (no padding), so dividing by
#' `box_sum_cpp(1, r)` gives an unbiased local mean near edges.
#'
#' @param x Numeric matrix (NA not allowed; use weights instead).
#' @param r Integer half-width.
#' @keywords internal
#' @noRd
box_sum_cpp <- function(x, r) {
    .Call(`_MycoHalo_box_sum_cpp`, x, r)
}

#' Marker-controlled watershed restricted to a mask (internal)
#'
#' Meyer's priority-flood algorithm. Each labelled marker pixel floods
#' neighbouring mask pixels in increasing order of `cost`; a pixel is
#' assigned to the first basin that reaches it. Mask pixels that cannot be
#' reached from any marker (disconnected fragments) stay 0.
#'
#' @param cost Numeric matrix (lower = flooded earlier), e.g. the negative
#'   distance transform for shape-based splitting.
#' @param markers Integer matrix, 0 = unlabelled, >0 = basin id.
#' @param mask Logical matrix of pixels that may be labelled.
#' @keywords internal
#' @noRd
watershed_cpp <- function(cost, markers, mask) {
    .Call(`_MycoHalo_watershed_cpp`, cost, markers, mask)
}

#' Iterated separable box filter (internal)
#' @param x Numeric matrix.
#' @param r Half-width of the box.
#' @param passes Number of passes (3 approximates a Gaussian).
#' @keywords internal
#' @noRd
box_blur_cpp <- function(x, r, passes = 3L) {
    .Call(`_MycoHalo_box_blur_cpp`, x, r, passes)
}

